### PR TITLE
Fixed plugin class not found :)

### PR DESCRIPTION
**Pull request by MasterlazorX**

### CODE REVIEW

**Comment by Darunia18** [comment]
Thanks, but this project has been abandoned for a long time. While I'd love to go back to it one day, I'm not sure when that will be. You are welcome to add what you want to the project. I'd love to see this plugin made one day.

**Comment by hexdro** [comment]
I think we should revive it honestly. :)

**Comment by 64FF00** [comment]
@Darunia18 @hexdro Poop

**Comment by Darunia18** [comment]
@hexdro Very true. I have things I still need to do before I'd be able to work on this project again, but I would love to go back to it! And PE has evolved so much since I first had this idea that it would be so much better and maybe easier to implement now.

**Pull request merged**
